option('tizen',
  type: 'boolean',
  value: false,
  description: 'enable tizen specific dependancy'
)

option('tzapp_path',
  type: 'string',
  value: '/usr/apps/',
  description: 'installation path for tizen app binary'
)
option('tzpackage_path',
  type: 'string',
  value: '/usr/share/packages/',
  description: 'installation path for registering tizen service app'
)

option('tizen_gcov',
  type: 'boolean',
  value: false,
  description: 'enable tizen specific gcov configuration'
)

option('enable_documentation',
  type: 'boolean',
  value: false,
  description: 'enable generating documentation by using doxygen'
)

option('libaurum_only',
  type: 'boolean',
  value: false,
  description: 'skip building grpc and protobuf protocol'
)

option('build_c_bindings',
  type: 'boolean',
  value: false,
  description: 'build c bindings to be called from rust code'
)
option('build_aurum_cli',
  type: 'boolean',
  value: false,
  description: 'build aurum-cli executable that wraps libaurum APIs'
)
