
libaurum_src += [
  files('Sel.cc'),
  files('UiDevice.cc'),
  files('UiObject.cc'),
  files('UiSelector.cc'),
  files('Comparer.cc'),
  files('Until.cc'),
  files('Waiter.cc'),
  files('PartialMatch.cc'),
  files('A11yEvent.cc'),
]

subdir('Accessibility')
subdir('ScreenAnalyzer')
subdir('Impl')
subdir('Runnable')
