//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class A11yEventInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal A11yEventInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(A11yEventInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~A11yEventInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_A11yEventInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public A11yEventInfo() : this(aurumPINVOKE.new_A11yEventInfo__SWIG_0(), true) {
  }

  public A11yEventInfo(A11yEvent event_, string name, string package) : this(aurumPINVOKE.new_A11yEventInfo__SWIG_1((int)event_, name, package), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public A11yEventInfo(A11yEvent event_, string name) : this(aurumPINVOKE.new_A11yEventInfo__SWIG_2((int)event_, name), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public A11yEventInfo(A11yEvent event_) : this(aurumPINVOKE.new_A11yEventInfo__SWIG_3((int)event_), true) {
  }

  public A11yEventInfo(string event_, string name, string package) : this(aurumPINVOKE.new_A11yEventInfo__SWIG_4(event_, name, package), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public A11yEventInfo(string event_, string name) : this(aurumPINVOKE.new_A11yEventInfo__SWIG_5(event_, name), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public A11yEventInfo(string event_) : this(aurumPINVOKE.new_A11yEventInfo__SWIG_6(event_), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public A11yEvent getEvent() {
    A11yEvent ret = (A11yEvent)aurumPINVOKE.A11yEventInfo_getEvent__SWIG_0(swigCPtr);
    return ret;
  }

  public A11yEvent getEvent(string event_) {
    A11yEvent ret = (A11yEvent)aurumPINVOKE.A11yEventInfo_getEvent__SWIG_1(swigCPtr, event_);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getName() {
    string ret = aurumPINVOKE.A11yEventInfo_getName(swigCPtr);
    return ret;
  }

  public string getPkg() {
    string ret = aurumPINVOKE.A11yEventInfo_getPkg(swigCPtr);
    return ret;
  }

}

}
