//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public enum AccessibleNodeInterface {
  ACTION = 0x0001,
  COLLECTION = 0X0002,
  COMPONENT = 0X0004,
  DOCUMENT = 0X0008,
  EDITABLETEXT = 0X0010,
  HYPERTEXT = 0X0020,
  IMAGE = 0X0040,
  SELECTION = 0X0080,
  TEXT = 0X0100,
  VALUE = 0X0200,
  ACCESSIBLE = 0X0400,
  TABLE = 0X0800,
  TABLECELL = 0X1000
}

}
