//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class AccessibleNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal AccessibleNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AccessibleNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AccessibleNode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          aurumPINVOKE.delete_AccessibleNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string description() {
    string ret = aurumPINVOKE.AccessibleNode_description(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int getChildCount() {
    int ret = aurumPINVOKE.AccessibleNode_getChildCount(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual AccessibleNode getChildAt(int index) {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleNode_getChildAt(swigCPtr, index);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual AccessibleNode getParent() {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleNode_getParent(swigCPtr);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual AccessibleNode next() {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleNode_next(swigCPtr);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual AccessibleNode prev() {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleNode_prev(swigCPtr);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual AccessibleNode first() {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleNode_first(swigCPtr);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual AccessibleNode last() {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleNode_last(swigCPtr);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void invalidate() {
    aurumPINVOKE.AccessibleNode_invalidate(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getId() {
    string ret = aurumPINVOKE.AccessibleNode_getId(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getType() {
    string ret = aurumPINVOKE.AccessibleNode_getType(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntRect getScreenBoundingBox() {
    IntRect ret = new IntRect(aurumPINVOKE.AccessibleNode_getScreenBoundingBox(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getOcrText() {
    string ret = aurumPINVOKE.AccessibleNode_getOcrText(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getWindowAngle() {
    int ret = aurumPINVOKE.AccessibleNode_getWindowAngle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getTargetAngle() {
    int ret = aurumPINVOKE.AccessibleNode_getTargetAngle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isFocusable() {
    bool ret = aurumPINVOKE.AccessibleNode_isFocusable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isFocused() {
    bool ret = aurumPINVOKE.AccessibleNode_isFocused(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isClickable() {
    bool ret = aurumPINVOKE.AccessibleNode_isClickable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isActive() {
    bool ret = aurumPINVOKE.AccessibleNode_isActive(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isShowing() {
    bool ret = aurumPINVOKE.AccessibleNode_isShowing(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getText() {
    string ret = aurumPINVOKE.AccessibleNode_getText(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOcrText(string text) {
    aurumPINVOKE.AccessibleNode_setOcrText(swigCPtr, text);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setWindowAngle(int windowAngle) {
    aurumPINVOKE.AccessibleNode_setWindowAngle(swigCPtr, windowAngle);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTargetAngle(int targetAngle) {
    aurumPINVOKE.AccessibleNode_setTargetAngle(swigCPtr, targetAngle);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getPkg() {
    string ret = aurumPINVOKE.AccessibleNode_getPkg(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getAutomationId() {
    string ret = aurumPINVOKE.AccessibleNode_getAutomationId(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getRole() {
    string ret = aurumPINVOKE.AccessibleNode_getRole(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getStyle() {
    string ret = aurumPINVOKE.AccessibleNode_getStyle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getToolkitName() {
    string ret = aurumPINVOKE.AccessibleNode_getToolkitName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntRect getWindowBoundingBox() {
    IntRect ret = new IntRect(aurumPINVOKE.AccessibleNode_getWindowBoundingBox(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getXPath() {
    string ret = aurumPINVOKE.AccessibleNode_getXPath(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMinValue() {
    double ret = aurumPINVOKE.AccessibleNode_getMinValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMaxValue() {
    double ret = aurumPINVOKE.AccessibleNode_getMaxValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getValue() {
    double ret = aurumPINVOKE.AccessibleNode_getValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getPid() {
    int ret = aurumPINVOKE.AccessibleNode_getPid(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getIncrement() {
    double ret = aurumPINVOKE.AccessibleNode_getIncrement(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntRect getTextMinBoundingRect() {
    IntRect ret = new IntRect(aurumPINVOKE.AccessibleNode_getTextMinBoundingRect(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getInterface() {
    string ret = aurumPINVOKE.AccessibleNode_getInterface(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDescription() {
    string ret = aurumPINVOKE.AccessibleNode_getDescription(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getImgSrc() {
    string ret = aurumPINVOKE.AccessibleNode_getImgSrc(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isCheckable() {
    bool ret = aurumPINVOKE.AccessibleNode_isCheckable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isChecked() {
    bool ret = aurumPINVOKE.AccessibleNode_isChecked(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isEnabled() {
    bool ret = aurumPINVOKE.AccessibleNode_isEnabled(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isLongClickable() {
    bool ret = aurumPINVOKE.AccessibleNode_isLongClickable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isScrollable() {
    bool ret = aurumPINVOKE.AccessibleNode_isScrollable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isSelectable() {
    bool ret = aurumPINVOKE.AccessibleNode_isSelectable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isSelected() {
    bool ret = aurumPINVOKE.AccessibleNode_isSelected(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isVisible() {
    bool ret = aurumPINVOKE.AccessibleNode_isVisible(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isHighlightable() {
    bool ret = aurumPINVOKE.AccessibleNode_isHighlightable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void print(int arg0) {
    aurumPINVOKE.AccessibleNode_print__SWIG_0(swigCPtr, arg0);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void print(int arg0, int arg1) {
    aurumPINVOKE.AccessibleNode_print__SWIG_1(swigCPtr, arg0, arg1);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateRoleName() {
    aurumPINVOKE.AccessibleNode_updateRoleName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateUniqueId() {
    aurumPINVOKE.AccessibleNode_updateUniqueId(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateName() {
    aurumPINVOKE.AccessibleNode_updateName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateApplication() {
    aurumPINVOKE.AccessibleNode_updateApplication(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateAttributes() {
    aurumPINVOKE.AccessibleNode_updateAttributes(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateStates() {
    aurumPINVOKE.AccessibleNode_updateStates(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateExtents() {
    aurumPINVOKE.AccessibleNode_updateExtents(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateXPath() {
    aurumPINVOKE.AccessibleNode_updateXPath(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateToolkitName() {
    aurumPINVOKE.AccessibleNode_updateToolkitName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateValue() {
    aurumPINVOKE.AccessibleNode_updateValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updatePid() {
    aurumPINVOKE.AccessibleNode_updatePid(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool setFocus() {
    bool ret = aurumPINVOKE.AccessibleNode_setFocus(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool moveTo() {
    bool ret = aurumPINVOKE.AccessibleNode_moveTo(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void updateTextMinBoundingRect() {
    aurumPINVOKE.AccessibleNode_updateTextMinBoundingRect(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateInterface() {
    aurumPINVOKE.AccessibleNode_updateInterface(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void refresh(bool updateAll) {
    aurumPINVOKE.AccessibleNode_refresh__SWIG_0(swigCPtr, updateAll);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void refresh() {
    aurumPINVOKE.AccessibleNode_refresh__SWIG_1(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool doAction(string action) {
    bool ret = aurumPINVOKE.AccessibleNode_doAction(swigCPtr, action);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool setValue(string text) {
    bool ret = aurumPINVOKE.AccessibleNode_setValue__SWIG_0(swigCPtr, text);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool setValue(double value) {
    bool ret = aurumPINVOKE.AccessibleNode_setValue__SWIG_1(swigCPtr, value);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool isValid() {
    bool ret = aurumPINVOKE.AccessibleNode_isValid(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setIncludeHidden(bool enabled) {
    aurumPINVOKE.AccessibleNode_setIncludeHidden(swigCPtr, enabled);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool getIncludeHidden() {
    bool ret = aurumPINVOKE.AccessibleNode_getIncludeHidden(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isSupporting(AccessibleNodeInterface thisIface) {
    bool ret = aurumPINVOKE.AccessibleNode_isSupporting(swigCPtr, (int)thisIface);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool hasFeatureProperty(NodeFeatureProperties prop) {
    bool ret = aurumPINVOKE.AccessibleNode_hasFeatureProperty(swigCPtr, (int)prop);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setFeatureProperty(NodeFeatureProperties prop, bool has) {
    aurumPINVOKE.AccessibleNode_setFeatureProperty(swigCPtr, (int)prop, has);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void resetFeatureProperty() {
    aurumPINVOKE.AccessibleNode_resetFeatureProperty(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
