//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class AccessibleWatcher : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal AccessibleWatcher(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AccessibleWatcher obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AccessibleWatcher() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          aurumPINVOKE.delete_AccessibleWatcher(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static AccessibleWatcher getInstance(AccessibleWatcher watcherImpl) {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleWatcher_getInstance__SWIG_0(AccessibleWatcher.getCPtr(watcherImpl));
    AccessibleWatcher ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleWatcher(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static AccessibleWatcher getInstance() {
    global::System.IntPtr cPtr = aurumPINVOKE.AccessibleWatcher_getInstance__SWIG_1();
    AccessibleWatcher ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleWatcher(cPtr, true);
    return ret;
  }

  public virtual void setXMLsync(bool sync) {
    aurumPINVOKE.AccessibleWatcher_setXMLsync(swigCPtr, sync);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool getWindowEventEmitted() {
    bool ret = aurumPINVOKE.AccessibleWatcher_getWindowEventEmitted(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
