//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class IDevice : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IDevice(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IDevice obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IDevice() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_IDevice(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual bool click(int x, int y) {
    bool ret = aurumPINVOKE.IDevice_click__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public virtual bool click(int x, int y, uint durationMs) {
    bool ret = aurumPINVOKE.IDevice_click__SWIG_1(swigCPtr, x, y, durationMs);
    return ret;
  }

  public virtual bool drag(int sx, int sy, int ex, int ey, int steps, int durationMs) {
    bool ret = aurumPINVOKE.IDevice_drag(swigCPtr, sx, sy, ex, ey, steps, durationMs);
    return ret;
  }

  public virtual int touchDown(int x, int y) {
    int ret = aurumPINVOKE.IDevice_touchDown(swigCPtr, x, y);
    return ret;
  }

  public virtual bool touchMove(int x, int y, int seq) {
    bool ret = aurumPINVOKE.IDevice_touchMove(swigCPtr, x, y, seq);
    return ret;
  }

  public virtual bool touchUp(int x, int y, int seq) {
    bool ret = aurumPINVOKE.IDevice_touchUp(swigCPtr, x, y, seq);
    return ret;
  }

  public virtual bool wheelUp(int amount, int durationMs) {
    bool ret = aurumPINVOKE.IDevice_wheelUp(swigCPtr, amount, durationMs);
    return ret;
  }

  public virtual bool wheelDown(int amount, int durationMs) {
    bool ret = aurumPINVOKE.IDevice_wheelDown(swigCPtr, amount, durationMs);
    return ret;
  }

  public virtual bool mouseDown(int x, int y, int button) {
    bool ret = aurumPINVOKE.IDevice_mouseDown(swigCPtr, x, y, button);
    return ret;
  }

  public virtual bool mouseMove(int x, int y, int button) {
    bool ret = aurumPINVOKE.IDevice_mouseMove(swigCPtr, x, y, button);
    return ret;
  }

  public virtual bool mouseUp(int x, int y, int button) {
    bool ret = aurumPINVOKE.IDevice_mouseUp(swigCPtr, x, y, button);
    return ret;
  }

  public virtual bool pressKeyCode(string keycode, KeyRequestType type) {
    bool ret = aurumPINVOKE.IDevice_pressKeyCode(swigCPtr, keycode, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool repeatKeyCode(string keycode, int intervalMs, int durationMs) {
    bool ret = aurumPINVOKE.IDevice_repeatKeyCode(swigCPtr, keycode, intervalMs, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool takeScreenshot(string path, bool asPixels, SWIGTYPE_p_p_void pixels, int angle) {
    bool ret = aurumPINVOKE.IDevice_takeScreenshot__SWIG_0(swigCPtr, path, asPixels, SWIGTYPE_p_p_void.getCPtr(pixels), angle);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool takeScreenshot(string path, bool asPixels, SWIGTYPE_p_p_void pixels) {
    bool ret = aurumPINVOKE.IDevice_takeScreenshot__SWIG_1(swigCPtr, path, asPixels, SWIGTYPE_p_p_void.getCPtr(pixels));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual long getSystemTime(TimeRequestType type) {
    long ret = aurumPINVOKE.IDevice_getSystemTime(swigCPtr, (int)type);
    return ret;
  }

  public virtual IntSize2D getScreenSize() {
    IntSize2D ret = new IntSize2D(aurumPINVOKE.IDevice_getScreenSize(swigCPtr), true);
    return ret;
  }

}

}
