//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class IntPoint2D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntPoint2D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntPoint2D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntPoint2D() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_IntPoint2D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IntPoint2D() : this(aurumPINVOKE.new_IntPoint2D__SWIG_0(), true) {
  }

  public IntPoint2D(IntPoint2D src) : this(aurumPINVOKE.new_IntPoint2D__SWIG_1(IntPoint2D.getCPtr(src)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntPoint2D(int x, int y) : this(aurumPINVOKE.new_IntPoint2D__SWIG_2(x, y), true) {
  }

  public bool equal(IntPoint2D rhs) {
    bool ret = aurumPINVOKE.IntPoint2D_equal(swigCPtr, IntPoint2D.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool diff(IntPoint2D rhs) {
    bool ret = aurumPINVOKE.IntPoint2D_diff(swigCPtr, IntPoint2D.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int x {
    set {
      aurumPINVOKE.IntPoint2D_x_set(swigCPtr, value);
    } 
    get {
      int ret = aurumPINVOKE.IntPoint2D_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      aurumPINVOKE.IntPoint2D_y_set(swigCPtr, value);
    } 
    get {
      int ret = aurumPINVOKE.IntPoint2D_y_get(swigCPtr);
      return ret;
    } 
  }

}

}
