//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class IntRect : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntRect(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntRect obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntRect() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_IntRect(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IntRect() : this(aurumPINVOKE.new_IntRect__SWIG_0(), true) {
  }

  public IntRect(IntPoint2D tl, IntPoint2D br) : this(aurumPINVOKE.new_IntRect__SWIG_1(IntPoint2D.getCPtr(tl), IntPoint2D.getCPtr(br)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntRect(int x1, int y1, int x2, int y2) : this(aurumPINVOKE.new_IntRect__SWIG_2(x1, y1, x2, y2), true) {
  }

  public IntRect(IntRect src) : this(aurumPINVOKE.new_IntRect__SWIG_3(IntRect.getCPtr(src)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntPoint2D midPoint() {
    IntPoint2D ret = new IntPoint2D(aurumPINVOKE.IntRect_midPoint(swigCPtr), true);
    return ret;
  }

  public int width() {
    int ret = aurumPINVOKE.IntRect_width(swigCPtr);
    return ret;
  }

  public int height() {
    int ret = aurumPINVOKE.IntRect_height(swigCPtr);
    return ret;
  }

  public bool isInRect(IntPoint2D point) {
    bool ret = aurumPINVOKE.IntRect_isInRect__SWIG_0(swigCPtr, IntPoint2D.getCPtr(point));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isInRect(IntRect rect) {
    bool ret = aurumPINVOKE.IntRect_isInRect__SWIG_1(swigCPtr, IntRect.getCPtr(rect));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool equal(IntRect rhs) {
    bool ret = aurumPINVOKE.IntRect_equal(swigCPtr, IntRect.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool diff(IntRect rhs) {
    bool ret = aurumPINVOKE.IntRect_diff(swigCPtr, IntRect.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPoint2D mTopLeft {
    set {
      aurumPINVOKE.IntRect_mTopLeft_set(swigCPtr, IntPoint2D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.IntRect_mTopLeft_get(swigCPtr);
      IntPoint2D ret = (cPtr == global::System.IntPtr.Zero) ? null : new IntPoint2D(cPtr, false);
      return ret;
    } 
  }

  public IntPoint2D mBottomRight {
    set {
      aurumPINVOKE.IntRect_mBottomRight_set(swigCPtr, IntPoint2D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.IntRect_mBottomRight_get(swigCPtr);
      IntPoint2D ret = (cPtr == global::System.IntPtr.Zero) ? null : new IntPoint2D(cPtr, false);
      return ret;
    } 
  }

}

}
