//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class IntSize2D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntSize2D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntSize2D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntSize2D() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_IntSize2D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IntSize2D() : this(aurumPINVOKE.new_IntSize2D__SWIG_0(), true) {
  }

  public IntSize2D(IntSize2D src) : this(aurumPINVOKE.new_IntSize2D__SWIG_1(IntSize2D.getCPtr(src)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntSize2D(int width, int height) : this(aurumPINVOKE.new_IntSize2D__SWIG_2(width, height), true) {
  }

  public bool equal(IntSize2D rhs) {
    bool ret = aurumPINVOKE.IntSize2D_equal(swigCPtr, IntSize2D.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool diff(IntSize2D rhs) {
    bool ret = aurumPINVOKE.IntSize2D_diff(swigCPtr, IntSize2D.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int width {
    set {
      aurumPINVOKE.IntSize2D_width_set(swigCPtr, value);
    } 
    get {
      int ret = aurumPINVOKE.IntSize2D_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      aurumPINVOKE.IntSize2D_height_set(swigCPtr, value);
    } 
    get {
      int ret = aurumPINVOKE.IntSize2D_height_get(swigCPtr);
      return ret;
    } 
  }

}

}
