//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class ISearchable : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ISearchable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ISearchable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ISearchable() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_ISearchable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual bool hasObject(UiSelector selector) {
    bool ret = aurumPINVOKE.ISearchable_hasObject(swigCPtr, UiSelector.getCPtr(selector));
    return ret;
  }

  public virtual UiObject findObject(UiSelector selector) {
    global::System.IntPtr cPtr = aurumPINVOKE.ISearchable_findObject(swigCPtr, UiSelector.getCPtr(selector));
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    return ret;
  }

  public virtual UiObjectVector findObjects(UiSelector selector) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.ISearchable_findObjects(swigCPtr, UiSelector.getCPtr(selector)), true);
    return ret;
  }

  public virtual UiObjectVector getMatches(UiSelector selector, bool earlyReturn) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.ISearchable_getMatches(swigCPtr, UiSelector.getCPtr(selector), earlyReturn), true);
    return ret;
  }

  public virtual UiObjectVector getMatchesInMatches(UiSelector firstSelector, UiSelector secondSelector, bool earlyReturn) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.ISearchable_getMatchesInMatches(swigCPtr, UiSelector.getCPtr(firstSelector), UiSelector.getCPtr(secondSelector), earlyReturn), true);
    return ret;
  }

}

}
