//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public enum NodeFeatureProperties {
  CHECKABLE = 0x0001,
  CHECKED = 0X0002,
  CLICKABLE = 0X0004,
  ENABLED = 0X0008,
  FOCUSABLE = 0X0010,
  FOCUSED = 0X0020,
  LONGCLICKABLE = 0X0040,
  SCROLLABLE = 0X0080,
  SELECTABLE = 0X0100,
  SELECTED = 0X0200,
  VISIBLE = 0X0400,
  SHOWING = 0X0800,
  ACTIVE = 0X1000,
  HIGHLIGHTABLE = 0X2000,
  INVALID = 0X4000
}

}
