//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class Node : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal Node(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Node obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Node() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          aurumPINVOKE.delete_Node(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Node(UiObject node, NodeVector children) : this(aurumPINVOKE.new_Node(UiObject.getCPtr(node), NodeVector.getCPtr(children)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiObject mNode {
    set {
      aurumPINVOKE.Node_mNode_set(swigCPtr, UiObject.getCPtr(value));
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.Node_mNode_get(swigCPtr);
      UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public NodeVector mChildren {
    set {
      aurumPINVOKE.Node_mChildren_set(swigCPtr, NodeVector.getCPtr(value));
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.Node_mChildren_get(swigCPtr);
      NodeVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodeVector(cPtr, false);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
