//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class Rect : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Rect(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Rect obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Rect() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_Rect(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Rect() : this(aurumPINVOKE.new_Rect__SWIG_0(), true) {
  }

  public Rect(Point2D tl, Point2D br) : this(aurumPINVOKE.new_Rect__SWIG_1(Point2D.getCPtr(tl), Point2D.getCPtr(br)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public Rect(int x1, int y1, int x2, int y2) : this(aurumPINVOKE.new_Rect__SWIG_2(x1, y1, x2, y2), true) {
  }

  public Rect(Rect src) : this(aurumPINVOKE.new_Rect__SWIG_3(Rect.getCPtr(src)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public Point2D midPoint() {
    Point2D ret = new Point2D(aurumPINVOKE.Rect_midPoint(swigCPtr), true);
    return ret;
  }

  public int width() {
    int ret = aurumPINVOKE.Rect_width(swigCPtr);
    return ret;
  }

  public int height() {
    int ret = aurumPINVOKE.Rect_height(swigCPtr);
    return ret;
  }

  public bool isInRect(Point2D point) {
    bool ret = aurumPINVOKE.Rect_isInRect__SWIG_0(swigCPtr, Point2D.getCPtr(point));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isInRect(Rect rect) {
    bool ret = aurumPINVOKE.Rect_isInRect__SWIG_1(swigCPtr, Rect.getCPtr(rect));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool equal(Rect rhs) {
    bool ret = aurumPINVOKE.Rect_equal(swigCPtr, Rect.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool diff(Rect rhs) {
    bool ret = aurumPINVOKE.Rect_diff(swigCPtr, Rect.getCPtr(rhs));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Point2D mTopLeft {
    set {
      aurumPINVOKE.Rect_mTopLeft_set(swigCPtr, Point2D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.Rect_mTopLeft_get(swigCPtr);
      Point2D ret = (cPtr == global::System.IntPtr.Zero) ? null : new Point2D(cPtr, false);
      return ret;
    } 
  }

  public Point2D mBottomRight {
    set {
      aurumPINVOKE.Rect_mBottomRight_set(swigCPtr, Point2D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.Rect_mBottomRight_get(swigCPtr);
      Point2D ret = (cPtr == global::System.IntPtr.Zero) ? null : new Point2D(cPtr, false);
      return ret;
    } 
  }

}

}
