//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class Sel : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Sel(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Sel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Sel() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_Sel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static UiSelector text(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.Sel_text(text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UiSelector type(string type) {
    global::System.IntPtr cPtr = aurumPINVOKE.Sel_type(type);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UiSelector style(string style) {
    global::System.IntPtr cPtr = aurumPINVOKE.Sel_style(style);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UiSelector depth(int depth) {
    global::System.IntPtr cPtr = aurumPINVOKE.Sel_depth(depth);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    return ret;
  }

  public Sel() : this(aurumPINVOKE.new_Sel(), true) {
  }

}

}
