//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class UiDevice : ISearchable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal UiDevice(global::System.IntPtr cPtr, bool cMemoryOwn) : base(aurumPINVOKE.UiDevice_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UiDevice obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          aurumPINVOKE.delete_UiDevice(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public bool click(int x, int y) {
    bool ret = aurumPINVOKE.UiDevice_click__SWIG_0(swigCPtr, x, y);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool click(int x, int y, uint durationMs) {
    bool ret = aurumPINVOKE.UiDevice_click__SWIG_1(swigCPtr, x, y, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool drag(int sx, int sy, int ex, int ey, int steps, int durationMs) {
    bool ret = aurumPINVOKE.UiDevice_drag(swigCPtr, sx, sy, ex, ey, steps, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int touchDown(int x, int y) {
    int ret = aurumPINVOKE.UiDevice_touchDown(swigCPtr, x, y);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool touchMove(int x, int y, int seq) {
    bool ret = aurumPINVOKE.UiDevice_touchMove(swigCPtr, x, y, seq);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool touchUp(int x, int y, int seq) {
    bool ret = aurumPINVOKE.UiDevice_touchUp(swigCPtr, x, y, seq);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool wheelUp(int amount, int durationMs) {
    bool ret = aurumPINVOKE.UiDevice_wheelUp(swigCPtr, amount, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool wheelDown(int amount, int durationMs) {
    bool ret = aurumPINVOKE.UiDevice_wheelDown(swigCPtr, amount, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool mouseDown(int x, int y, int button) {
    bool ret = aurumPINVOKE.UiDevice_mouseDown(swigCPtr, x, y, button);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool mouseMove(int x, int y, int button) {
    bool ret = aurumPINVOKE.UiDevice_mouseMove(swigCPtr, x, y, button);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool mouseUp(int x, int y, int button) {
    bool ret = aurumPINVOKE.UiDevice_mouseUp(swigCPtr, x, y, button);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressKeyCode(string keycode, KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressKeyCode(swigCPtr, keycode, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool repeatKeyCode(string keycode, int intervalMs, int durationMs) {
    bool ret = aurumPINVOKE.UiDevice_repeatKeyCode(swigCPtr, keycode, intervalMs, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool takeScreenshot(string path, bool asPixels, SWIGTYPE_p_p_void pixels, int angle) {
    bool ret = aurumPINVOKE.UiDevice_takeScreenshot__SWIG_0(swigCPtr, path, asPixels, SWIGTYPE_p_p_void.getCPtr(pixels), angle);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool takeScreenshot(string path, bool asPixels, SWIGTYPE_p_p_void pixels) {
    bool ret = aurumPINVOKE.UiDevice_takeScreenshot__SWIG_1(swigCPtr, path, asPixels, SWIGTYPE_p_p_void.getCPtr(pixels));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long getSystemTime(TimeRequestType type) {
    long ret = aurumPINVOKE.UiDevice_getSystemTime(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntSize2D getScreenSize() {
    IntSize2D ret = new IntSize2D(aurumPINVOKE.UiDevice_getScreenSize(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool hasObject(UiSelector selector) {
    bool ret = aurumPINVOKE.UiDevice_hasObject(swigCPtr, UiSelector.getCPtr(selector));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObject findObject(UiSelector selector) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiDevice_findObject(swigCPtr, UiSelector.getCPtr(selector));
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObjectVector findObjects(UiSelector selector) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiDevice_findObjects(swigCPtr, UiSelector.getCPtr(selector)), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObjectVector getMatches(UiSelector selector, bool earlyReturn) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiDevice_getMatches(swigCPtr, UiSelector.getCPtr(selector), earlyReturn), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObjectVector getMatchesInMatches(UiSelector firstSelector, UiSelector secondSelector, bool earlyReturn) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiDevice_getMatchesInMatches(swigCPtr, UiSelector.getCPtr(firstSelector), UiSelector.getCPtr(secondSelector), earlyReturn), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool waitFor(SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t condition) {
    bool ret = aurumPINVOKE.UiDevice_waitFor__SWIG_0(swigCPtr, SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t.getCPtr(condition));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject waitFor(SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiDevice_waitFor__SWIG_1(swigCPtr, SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t.getCPtr(condition));
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool waitForEvents(A11yEvent type, int timeout, string packageName) {
    bool ret = aurumPINVOKE.UiDevice_waitForEvents__SWIG_0(swigCPtr, (int)type, timeout, packageName);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool waitForEvents(A11yEvent type, int timeout) {
    bool ret = aurumPINVOKE.UiDevice_waitForEvents__SWIG_1(swigCPtr, (int)type, timeout);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool sendKeyAndWaitForEvents(string keycode, A11yEvent type, int timeout, string packageName) {
    bool ret = aurumPINVOKE.UiDevice_sendKeyAndWaitForEvents__SWIG_0(swigCPtr, keycode, (int)type, timeout, packageName);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool sendKeyAndWaitForEvents(string keycode, A11yEvent type, int timeout) {
    bool ret = aurumPINVOKE.UiDevice_sendKeyAndWaitForEvents__SWIG_1(swigCPtr, keycode, (int)type, timeout);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static UiDevice getInstance(IDevice deviceImpl) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiDevice_getInstance__SWIG_0(IDevice.getCPtr(deviceImpl));
    UiDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiDevice(cPtr, true);
    return ret;
  }

  public static UiDevice getInstance() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiDevice_getInstance__SWIG_1();
    UiDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiDevice(cPtr, true);
    return ret;
  }

  public bool getExternalAppLaunched() {
    bool ret = aurumPINVOKE.UiDevice_getExternalAppLaunched(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getWindowAngle() {
    int ret = aurumPINVOKE.UiDevice_getWindowAngle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getTargetAngle() {
    int ret = aurumPINVOKE.UiDevice_getTargetAngle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool generateKey(KeyType keyType, KeyRequestType keyReqestType) {
    bool ret = aurumPINVOKE.UiDevice_generateKey(swigCPtr, (int)keyType, (int)keyReqestType);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressBack(KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressBack(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressHome(KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressHome(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressMenu(KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressMenu(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressVolUp(KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressVolUp(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressVolDown(KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressVolDown(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool pressPower(KeyRequestType type) {
    bool ret = aurumPINVOKE.UiDevice_pressPower(swigCPtr, (int)type);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
