//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class UiObject : ISearchable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal UiObject(global::System.IntPtr cPtr, bool cMemoryOwn) : base(aurumPINVOKE.UiObject_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UiObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          aurumPINVOKE.delete_UiObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public UiObject(UiDevice device, UiSelector selector, AccessibleNode node) : this(aurumPINVOKE.new_UiObject__SWIG_0(UiDevice.getCPtr(device), UiSelector.getCPtr(selector), AccessibleNode.getCPtr(node)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiObject(UiObject src) : this(aurumPINVOKE.new_UiObject__SWIG_2(UiObject.getCPtr(src)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiObject() : this(aurumPINVOKE.new_UiObject__SWIG_3(), true) {
  }

  public UiSelector getSelector() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_getSelector(swigCPtr);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool hasObject(UiSelector selector) {
    bool ret = aurumPINVOKE.UiObject_hasObject(swigCPtr, UiSelector.getCPtr(selector));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObject findObject(UiSelector selector) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_findObject(swigCPtr, UiSelector.getCPtr(selector));
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObjectVector findObjects(UiSelector selector) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiObject_findObjects(swigCPtr, UiSelector.getCPtr(selector)), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObjectVector getMatches(UiSelector selector, bool earlyReturn) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiObject_getMatches(swigCPtr, UiSelector.getCPtr(selector), earlyReturn), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UiObjectVector getMatchesInMatches(UiSelector firstSelector, UiSelector secondSelector, bool earlyReturn) {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiObject_getMatchesInMatches(swigCPtr, UiSelector.getCPtr(firstSelector), UiSelector.getCPtr(secondSelector), earlyReturn), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool waitFor(SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t condition) {
    bool ret = aurumPINVOKE.UiObject_waitFor__SWIG_0(swigCPtr, SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t.getCPtr(condition));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject waitFor(SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_waitFor__SWIG_1(swigCPtr, SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t.getCPtr(condition));
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool waitFor(SWIGTYPE_p_std__functionT_bool_fAurum__UiObject_const_pF_t condition) {
    bool ret = aurumPINVOKE.UiObject_waitFor__SWIG_2(swigCPtr, SWIGTYPE_p_std__functionT_bool_fAurum__UiObject_const_pF_t.getCPtr(condition));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getId() {
    string ret = aurumPINVOKE.UiObject_getId(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getType() {
    string ret = aurumPINVOKE.UiObject_getType(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntRect getScreenBoundingBox() {
    IntRect ret = new IntRect(aurumPINVOKE.UiObject_getScreenBoundingBox(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getOcrText() {
    string ret = aurumPINVOKE.UiObject_getOcrText(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getWindowAngle() {
    int ret = aurumPINVOKE.UiObject_getWindowAngle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getTargetAngle() {
    int ret = aurumPINVOKE.UiObject_getTargetAngle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isFocusable() {
    bool ret = aurumPINVOKE.UiObject_isFocusable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isFocused() {
    bool ret = aurumPINVOKE.UiObject_isFocused(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isClickable() {
    bool ret = aurumPINVOKE.UiObject_isClickable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isActive() {
    bool ret = aurumPINVOKE.UiObject_isActive(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isShowing() {
    bool ret = aurumPINVOKE.UiObject_isShowing(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject getParent() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_getParent(swigCPtr);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getChildCount() {
    int ret = aurumPINVOKE.UiObject_getChildCount(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObjectVector getChildren() {
    UiObjectVector ret = new UiObjectVector(aurumPINVOKE.UiObject_getChildren(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject getChildAt(int index) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_getChildAt(swigCPtr, index);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Node getDescendant() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_getDescendant(swigCPtr);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getApplicationPackage() {
    string ret = aurumPINVOKE.UiObject_getApplicationPackage(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getAutomationId() {
    string ret = aurumPINVOKE.UiObject_getAutomationId(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getElementStyle() {
    string ret = aurumPINVOKE.UiObject_getElementStyle(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getText() {
    string ret = aurumPINVOKE.UiObject_getText(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getRole() {
    string ret = aurumPINVOKE.UiObject_getRole(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getToolkitName() {
    string ret = aurumPINVOKE.UiObject_getToolkitName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getXPath() {
    string ret = aurumPINVOKE.UiObject_getXPath(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool setText(string text) {
    bool ret = aurumPINVOKE.UiObject_setText(swigCPtr, text);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOcrText(string text) {
    aurumPINVOKE.UiObject_setOcrText(swigCPtr, text);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntRect getWindowBoundingBox() {
    IntRect ret = new IntRect(aurumPINVOKE.UiObject_getWindowBoundingBox(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMinValue() {
    double ret = aurumPINVOKE.UiObject_getMinValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getMaxValue() {
    double ret = aurumPINVOKE.UiObject_getMaxValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getValue() {
    double ret = aurumPINVOKE.UiObject_getValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getPid() {
    int ret = aurumPINVOKE.UiObject_getPid(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getIncrement() {
    double ret = aurumPINVOKE.UiObject_getIncrement(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntRect getTextMinBoundingRect() {
    IntRect ret = new IntRect(aurumPINVOKE.UiObject_getTextMinBoundingRect(swigCPtr), true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getInterface() {
    string ret = aurumPINVOKE.UiObject_getInterface(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool setValue(double value) {
    bool ret = aurumPINVOKE.UiObject_setValue(swigCPtr, value);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDescription() {
    string ret = aurumPINVOKE.UiObject_getDescription(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getImgSrc() {
    string ret = aurumPINVOKE.UiObject_getImgSrc(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isCheckable() {
    bool ret = aurumPINVOKE.UiObject_isCheckable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isChecked() {
    bool ret = aurumPINVOKE.UiObject_isChecked(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isEnabled() {
    bool ret = aurumPINVOKE.UiObject_isEnabled(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isLongClickable() {
    bool ret = aurumPINVOKE.UiObject_isLongClickable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isScrollable() {
    bool ret = aurumPINVOKE.UiObject_isScrollable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isSelectable() {
    bool ret = aurumPINVOKE.UiObject_isSelectable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isSelected() {
    bool ret = aurumPINVOKE.UiObject_isSelected(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isVisible() {
    bool ret = aurumPINVOKE.UiObject_isVisible(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isHighlightable() {
    bool ret = aurumPINVOKE.UiObject_isHighlightable(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void click() {
    aurumPINVOKE.UiObject_click(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void longClick(uint durationMs) {
    aurumPINVOKE.UiObject_longClick__SWIG_0(swigCPtr, durationMs);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void longClick() {
    aurumPINVOKE.UiObject_longClick__SWIG_1(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool DoAtspiActivate() {
    bool ret = aurumPINVOKE.UiObject_DoAtspiActivate(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void updateRoleName() {
    aurumPINVOKE.UiObject_updateRoleName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateUniqueId() {
    aurumPINVOKE.UiObject_updateUniqueId(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateName() {
    aurumPINVOKE.UiObject_updateName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateApplication() {
    aurumPINVOKE.UiObject_updateApplication(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateAttributes() {
    aurumPINVOKE.UiObject_updateAttributes(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateStates() {
    aurumPINVOKE.UiObject_updateStates(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateExtents() {
    aurumPINVOKE.UiObject_updateExtents(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateXPath() {
    aurumPINVOKE.UiObject_updateXPath(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateValue() {
    aurumPINVOKE.UiObject_updateValue(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updatePid() {
    aurumPINVOKE.UiObject_updatePid(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateToolkitName() {
    aurumPINVOKE.UiObject_updateToolkitName(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateTextMinBoundingRect() {
    aurumPINVOKE.UiObject_updateTextMinBoundingRect(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateInterface() {
    aurumPINVOKE.UiObject_updateInterface(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool setFocus() {
    bool ret = aurumPINVOKE.UiObject_setFocus(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool moveTo() {
    bool ret = aurumPINVOKE.UiObject_moveTo(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void refresh() {
    aurumPINVOKE.UiObject_refresh(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isValid() {
    bool ret = aurumPINVOKE.UiObject_isValid(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public AccessibleNode getAccessibleNode() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_getAccessibleNode(swigCPtr);
    AccessibleNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new AccessibleNode(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject next() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_next(swigCPtr);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject prev() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_prev(swigCPtr);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject first() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_first(swigCPtr);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiObject last() {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObject_last(swigCPtr);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setIncludeHidden(bool enabled) {
    aurumPINVOKE.UiObject_setIncludeHidden(swigCPtr, enabled);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getIncludeHidden() {
    bool ret = aurumPINVOKE.UiObject_getIncludeHidden(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
