//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class UiObjectVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<UiObject>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UiObjectVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UiObjectVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UiObjectVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_UiObjectVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UiObjectVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (UiObject element in c) {
      this.Add(element);
    }
  }

  public UiObjectVector(global::System.Collections.Generic.IEnumerable<UiObject> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (UiObject element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public UiObject this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(UiObject[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(UiObject[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, UiObject[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public UiObject[] ToArray() {
    UiObject[] array = new UiObject[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<UiObject> global::System.Collections.Generic.IEnumerable<UiObject>.GetEnumerator() {
    return new UiObjectVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new UiObjectVectorEnumerator(this);
  }

  public UiObjectVectorEnumerator GetEnumerator() {
    return new UiObjectVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class UiObjectVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<UiObject>
  {
    private UiObjectVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public UiObjectVectorEnumerator(UiObjectVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public UiObject Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (UiObject)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    aurumPINVOKE.UiObjectVector_Clear(swigCPtr);
  }

  public void Add(UiObject x) {
    aurumPINVOKE.UiObjectVector_Add(swigCPtr, UiObject.getCPtr(x));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = aurumPINVOKE.UiObjectVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = aurumPINVOKE.UiObjectVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    aurumPINVOKE.UiObjectVector_reserve(swigCPtr, n);
  }

  public UiObjectVector() : this(aurumPINVOKE.new_UiObjectVector__SWIG_0(), true) {
  }

  public UiObjectVector(UiObjectVector other) : this(aurumPINVOKE.new_UiObjectVector__SWIG_1(UiObjectVector.getCPtr(other)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiObjectVector(int capacity) : this(aurumPINVOKE.new_UiObjectVector__SWIG_2(capacity), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  private UiObject getitemcopy(int index) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObjectVector_getitemcopy(swigCPtr, index);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private UiObject getitem(int index) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObjectVector_getitem(swigCPtr, index);
    UiObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObject(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, UiObject val) {
    aurumPINVOKE.UiObjectVector_setitem(swigCPtr, index, UiObject.getCPtr(val));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(UiObjectVector values) {
    aurumPINVOKE.UiObjectVector_AddRange(swigCPtr, UiObjectVector.getCPtr(values));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiObjectVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObjectVector_GetRange(swigCPtr, index, count);
    UiObjectVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObjectVector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, UiObject x) {
    aurumPINVOKE.UiObjectVector_Insert(swigCPtr, index, UiObject.getCPtr(x));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, UiObjectVector values) {
    aurumPINVOKE.UiObjectVector_InsertRange(swigCPtr, index, UiObjectVector.getCPtr(values));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    aurumPINVOKE.UiObjectVector_RemoveAt(swigCPtr, index);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    aurumPINVOKE.UiObjectVector_RemoveRange(swigCPtr, index, count);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public static UiObjectVector Repeat(UiObject value, int count) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiObjectVector_Repeat(UiObject.getCPtr(value), count);
    UiObjectVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiObjectVector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    aurumPINVOKE.UiObjectVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    aurumPINVOKE.UiObjectVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, UiObjectVector values) {
    aurumPINVOKE.UiObjectVector_SetRange(swigCPtr, index, UiObjectVector.getCPtr(values));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
