//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class UiSelectorVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<UiSelector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UiSelectorVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UiSelectorVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UiSelectorVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_UiSelectorVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UiSelectorVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (UiSelector element in c) {
      this.Add(element);
    }
  }

  public UiSelectorVector(global::System.Collections.Generic.IEnumerable<UiSelector> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (UiSelector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public UiSelector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(UiSelector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(UiSelector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, UiSelector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public UiSelector[] ToArray() {
    UiSelector[] array = new UiSelector[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<UiSelector> global::System.Collections.Generic.IEnumerable<UiSelector>.GetEnumerator() {
    return new UiSelectorVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new UiSelectorVectorEnumerator(this);
  }

  public UiSelectorVectorEnumerator GetEnumerator() {
    return new UiSelectorVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class UiSelectorVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<UiSelector>
  {
    private UiSelectorVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public UiSelectorVectorEnumerator(UiSelectorVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public UiSelector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (UiSelector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    aurumPINVOKE.UiSelectorVector_Clear(swigCPtr);
  }

  public void Add(UiSelector x) {
    aurumPINVOKE.UiSelectorVector_Add(swigCPtr, UiSelector.getCPtr(x));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = aurumPINVOKE.UiSelectorVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = aurumPINVOKE.UiSelectorVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    aurumPINVOKE.UiSelectorVector_reserve(swigCPtr, n);
  }

  public UiSelectorVector() : this(aurumPINVOKE.new_UiSelectorVector__SWIG_0(), true) {
  }

  public UiSelectorVector(UiSelectorVector other) : this(aurumPINVOKE.new_UiSelectorVector__SWIG_1(UiSelectorVector.getCPtr(other)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiSelectorVector(int capacity) : this(aurumPINVOKE.new_UiSelectorVector__SWIG_2(capacity), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  private UiSelector getitemcopy(int index) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelectorVector_getitemcopy(swigCPtr, index);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private UiSelector getitem(int index) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelectorVector_getitem(swigCPtr, index);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, UiSelector val) {
    aurumPINVOKE.UiSelectorVector_setitem(swigCPtr, index, UiSelector.getCPtr(val));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(UiSelectorVector values) {
    aurumPINVOKE.UiSelectorVector_AddRange(swigCPtr, UiSelectorVector.getCPtr(values));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public UiSelectorVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelectorVector_GetRange(swigCPtr, index, count);
    UiSelectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelectorVector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, UiSelector x) {
    aurumPINVOKE.UiSelectorVector_Insert(swigCPtr, index, UiSelector.getCPtr(x));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, UiSelectorVector values) {
    aurumPINVOKE.UiSelectorVector_InsertRange(swigCPtr, index, UiSelectorVector.getCPtr(values));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    aurumPINVOKE.UiSelectorVector_RemoveAt(swigCPtr, index);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    aurumPINVOKE.UiSelectorVector_RemoveRange(swigCPtr, index, count);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public static UiSelectorVector Repeat(UiSelector value, int count) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelectorVector_Repeat(UiSelector.getCPtr(value), count);
    UiSelectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelectorVector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    aurumPINVOKE.UiSelectorVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    aurumPINVOKE.UiSelectorVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, UiSelectorVector values) {
    aurumPINVOKE.UiSelectorVector_SetRange(swigCPtr, index, UiSelectorVector.getCPtr(values));
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
