//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class UiSelector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal UiSelector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UiSelector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UiSelector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          aurumPINVOKE.delete_UiSelector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UiSelector() : this(aurumPINVOKE.new_UiSelector(), true) {
  }

  public string description() {
    string ret = aurumPINVOKE.UiSelector_description__SWIG_0(swigCPtr);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector id(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_id(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector automationid(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_automationid(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector text(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_text(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector ocrText(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_ocrText(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector textPartialMatch(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_textPartialMatch(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector pkg(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_pkg(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector role(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_role(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector type(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_type(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector style(string text) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_style(swigCPtr, text);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector depth(int depth) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_depth__SWIG_0(swigCPtr, depth);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector depth(int minDepth, int maxDepth) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_depth__SWIG_1(swigCPtr, minDepth, maxDepth);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector minDepth(int depth) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_minDepth(swigCPtr, depth);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector maxDepth(int depth) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_maxDepth(swigCPtr, depth);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isChecked(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isChecked(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isCheckable(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isCheckable(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isClickable(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isClickable(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isEnabled(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isEnabled(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isFocused(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isFocused(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isFocusable(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isFocusable(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isScrollable(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isScrollable(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isSelected(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isSelected(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isShowing(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isShowing(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isActive(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isActive(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isVisible(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isVisible(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isSelectable(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isSelectable(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector isHighlightable(bool condition) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_isHighlightable(swigCPtr, condition);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector hasChild(UiSelector child) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_hasChild(swigCPtr, UiSelector.getCPtr(child));
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector fromParent(UiSelector parent) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_fromParent(swigCPtr, UiSelector.getCPtr(parent));
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector xpath(string xpath) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_xpath(swigCPtr, xpath);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector geometry(Rect geometry, bool isEqual) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_geometry(swigCPtr, Rect.getCPtr(geometry), isEqual);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector description(string description) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_description__SWIG_1(swigCPtr, description);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UiSelector imgSrc(string imgSrc) {
    global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_imgSrc(swigCPtr, imgSrc);
    UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string mId {
    set {
      aurumPINVOKE.UiSelector_mId_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mId_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mAutomationId {
    set {
      aurumPINVOKE.UiSelector_mAutomationId_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mAutomationId_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mRole {
    set {
      aurumPINVOKE.UiSelector_mRole_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mRole_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mText {
    set {
      aurumPINVOKE.UiSelector_mText_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mText_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mPkg {
    set {
      aurumPINVOKE.UiSelector_mPkg_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mPkg_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mType {
    set {
      aurumPINVOKE.UiSelector_mType_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mType_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mStyle {
    set {
      aurumPINVOKE.UiSelector_mStyle_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mStyle_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mTextPartialMatch {
    set {
      aurumPINVOKE.UiSelector_mTextPartialMatch_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mTextPartialMatch_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mXPath {
    set {
      aurumPINVOKE.UiSelector_mXPath_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mXPath_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mOcrText {
    set {
      aurumPINVOKE.UiSelector_mOcrText_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mOcrText_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mDescription {
    set {
      aurumPINVOKE.UiSelector_mDescription_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mDescription_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mImgSrc {
    set {
      aurumPINVOKE.UiSelector_mImgSrc_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = aurumPINVOKE.UiSelector_mImgSrc_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchId {
    set {
      aurumPINVOKE.UiSelector_mMatchId_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchId_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchAutomationId {
    set {
      aurumPINVOKE.UiSelector_mMatchAutomationId_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchAutomationId_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchRole {
    set {
      aurumPINVOKE.UiSelector_mMatchRole_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchRole_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchText {
    set {
      aurumPINVOKE.UiSelector_mMatchText_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchText_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchPkg {
    set {
      aurumPINVOKE.UiSelector_mMatchPkg_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchPkg_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchType {
    set {
      aurumPINVOKE.UiSelector_mMatchType_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchType_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchStyle {
    set {
      aurumPINVOKE.UiSelector_mMatchStyle_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchStyle_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchTextPartialMatch {
    set {
      aurumPINVOKE.UiSelector_mMatchTextPartialMatch_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchTextPartialMatch_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchXPath {
    set {
      aurumPINVOKE.UiSelector_mMatchXPath_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchXPath_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchOcrText {
    set {
      aurumPINVOKE.UiSelector_mMatchOcrText_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchOcrText_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchGeometry {
    set {
      aurumPINVOKE.UiSelector_mMatchGeometry_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchGeometry_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchDescription {
    set {
      aurumPINVOKE.UiSelector_mMatchDescription_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchDescription_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchImgSrc {
    set {
      aurumPINVOKE.UiSelector_mMatchImgSrc_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchImgSrc_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchChecked {
    set {
      aurumPINVOKE.UiSelector_mMatchChecked_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchChecked_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchCheckable {
    set {
      aurumPINVOKE.UiSelector_mMatchCheckable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchCheckable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchClickable {
    set {
      aurumPINVOKE.UiSelector_mMatchClickable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchClickable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchEnabled {
    set {
      aurumPINVOKE.UiSelector_mMatchEnabled_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchEnabled_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchFocused {
    set {
      aurumPINVOKE.UiSelector_mMatchFocused_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchFocused_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchFocusable {
    set {
      aurumPINVOKE.UiSelector_mMatchFocusable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchFocusable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchScrollable {
    set {
      aurumPINVOKE.UiSelector_mMatchScrollable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchScrollable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchSelected {
    set {
      aurumPINVOKE.UiSelector_mMatchSelected_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchSelected_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchShowing {
    set {
      aurumPINVOKE.UiSelector_mMatchShowing_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchShowing_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchActive {
    set {
      aurumPINVOKE.UiSelector_mMatchActive_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchActive_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchVisible {
    set {
      aurumPINVOKE.UiSelector_mMatchVisible_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchVisible_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchSelectable {
    set {
      aurumPINVOKE.UiSelector_mMatchSelectable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchSelectable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mMatchHighlightable {
    set {
      aurumPINVOKE.UiSelector_mMatchHighlightable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mMatchHighlightable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int mMinDepth {
    set {
      aurumPINVOKE.UiSelector_mMinDepth_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = aurumPINVOKE.UiSelector_mMinDepth_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int mMaxDepth {
    set {
      aurumPINVOKE.UiSelector_mMaxDepth_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = aurumPINVOKE.UiSelector_mMaxDepth_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIschecked {
    set {
      aurumPINVOKE.UiSelector_mIschecked_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIschecked_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIscheckable {
    set {
      aurumPINVOKE.UiSelector_mIscheckable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIscheckable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsclickable {
    set {
      aurumPINVOKE.UiSelector_mIsclickable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsclickable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsenabled {
    set {
      aurumPINVOKE.UiSelector_mIsenabled_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsenabled_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsfocused {
    set {
      aurumPINVOKE.UiSelector_mIsfocused_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsfocused_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsfocusable {
    set {
      aurumPINVOKE.UiSelector_mIsfocusable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsfocusable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsscrollable {
    set {
      aurumPINVOKE.UiSelector_mIsscrollable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsscrollable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsselected {
    set {
      aurumPINVOKE.UiSelector_mIsselected_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsselected_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsshowing {
    set {
      aurumPINVOKE.UiSelector_mIsshowing_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsshowing_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsactive {
    set {
      aurumPINVOKE.UiSelector_mIsactive_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsactive_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsvisible {
    set {
      aurumPINVOKE.UiSelector_mIsvisible_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsvisible_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIsselectable {
    set {
      aurumPINVOKE.UiSelector_mIsselectable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIsselectable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mIshighlightable {
    set {
      aurumPINVOKE.UiSelector_mIshighlightable_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mIshighlightable_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool mGeometryIsEqual {
    set {
      aurumPINVOKE.UiSelector_mGeometryIsEqual_set(swigCPtr, value);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = aurumPINVOKE.UiSelector_mGeometryIsEqual_get(swigCPtr);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public UiSelectorVector mChild {
    set {
      aurumPINVOKE.UiSelector_mChild_set(swigCPtr, UiSelectorVector.getCPtr(value));
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_mChild_get(swigCPtr);
      UiSelectorVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelectorVector(cPtr, false);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public UiSelector mParent {
    set {
      aurumPINVOKE.UiSelector_mParent_set(swigCPtr, UiSelector.getCPtr(value));
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_mParent_get(swigCPtr);
      UiSelector ret = (cPtr == global::System.IntPtr.Zero) ? null : new UiSelector(cPtr, true);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Rect mGeometry {
    set {
      aurumPINVOKE.UiSelector_mGeometry_set(swigCPtr, Rect.getCPtr(value));
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = aurumPINVOKE.UiSelector_mGeometry_get(swigCPtr);
      Rect ret = (cPtr == global::System.IntPtr.Zero) ? null : new Rect(cPtr, false);
      if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
