//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class Until : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Until(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Until obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Until() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t hasObject(UiSelector selector) {
    SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t ret = new SWIGTYPE_p_std__functionT_bool_fAurum__ISearchable_const_pF_t(aurumPINVOKE.Until_hasObject(UiSelector.getCPtr(selector)), true);
    return ret;
  }

  public static SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t findObject(UiSelector selector) {
    SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t ret = new SWIGTYPE_p_std__functionT_std__shared_ptrT_Aurum__UiObject_t_fAurum__ISearchable_const_pF_t(aurumPINVOKE.Until_findObject(UiSelector.getCPtr(selector)), true);
    return ret;
  }

  public static SWIGTYPE_p_std__functionT_bool_fAurum__UiObject_const_pF_t checkable(bool isCheckable) {
    SWIGTYPE_p_std__functionT_bool_fAurum__UiObject_const_pF_t ret = new SWIGTYPE_p_std__functionT_bool_fAurum__UiObject_const_pF_t(aurumPINVOKE.Until_checkable(isCheckable), true);
    return ret;
  }

  public static SWIGTYPE_p_std__functionT_std__vectorT_std__shared_ptrT_Aurum__UiObject_t_t_fAurum__ISearchable_const_pF_t findObjects(UiSelector selector) {
    SWIGTYPE_p_std__functionT_std__vectorT_std__shared_ptrT_Aurum__UiObject_t_t_fAurum__ISearchable_const_pF_t ret = new SWIGTYPE_p_std__functionT_std__vectorT_std__shared_ptrT_Aurum__UiObject_t_t_fAurum__ISearchable_const_pF_t(aurumPINVOKE.Until_findObjects(UiSelector.getCPtr(selector)), true);
    return ret;
  }

}

}
