//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aurum {

public class Waiter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Waiter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Waiter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Waiter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          aurumPINVOKE.delete_Waiter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Waiter(ISearchable searchableObject, UiObject uiObject, int timeout) : this(aurumPINVOKE.new_Waiter__SWIG_0(ISearchable.getCPtr(searchableObject), UiObject.getCPtr(uiObject), timeout), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public Waiter(ISearchable searchableObject, UiObject uiObject) : this(aurumPINVOKE.new_Waiter__SWIG_1(ISearchable.getCPtr(searchableObject), UiObject.getCPtr(uiObject)), true) {
    if (aurumPINVOKE.SWIGPendingException.Pending) throw aurumPINVOKE.SWIGPendingException.Retrieve();
  }

  public Waiter(ISearchable searchableObject) : this(aurumPINVOKE.new_Waiter__SWIG_2(ISearchable.getCPtr(searchableObject)), true) {
  }

}

}
