if get_option('tizen') == true
    libaurum_src += [
        files('AtspiAccessibleApplication.cc'),
        files('AtspiAccessibleWindow.cc'),
        files('AtspiAccessibleNode.cc'),
        files('AtspiAccessibleWatcher.cc'),
        files('AtspiAccessibleAppManager.cc'),
        files('AtspiWrapper.cc'),
        files('AtspiMatchRuleConvertor.cc'),
    ]
endif

libaurum_src += [
    files('MockAccessibleApplication.cc'),
    files('MockAccessibleWindow.cc'),
    files('MockAccessibleNode.cc'),
    files('MockAccessibleWatcher.cc'),
    files('MockAccessibleAppManager.cc'),
]
