    libaurum_src += [
        files('AtspiAccessibleApplication.cc'),
        files('AtspiAccessibleWindow.cc'),
        files('AtspiAccessibleNode.cc'),
        files('AtspiAccessibleWatcher.cc'),
    ]

    libaurum_src += [
        files('MockAccessibleApplication.cc'),
        files('MockAccessibleWindow.cc'),
        files('MockAccessibleNode.cc'),
        files('MockAccessibleWatcher.cc'),
    ]